# cloudbuild.yaml
substitutions:
  _REGION: "us-east1"                         # set to your Artifact Registry + Cloud Run region
  _REPO: "cicd-artifact-repo"
  _SERVICE: "bishopllc-storefront-app"

options:
  logging: CLOUD_LOGGING_ONLY                 # or GCS_ONLY with logsBucket if preferred

steps:
  # 1) BUILD container
  - id: "BUILD docker container"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA"
      - "."

  # 2) PUSH to Artifact Registry
  - id: "PUSH to Artifact Registry"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA"

  # 2.5) LOOK UP DIGEST for the just-pushed tag
  - id: "RESOLVE digest"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -ceu
      - |
       REF="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA"
       DIGEST=$(gcloud artifacts docker images describe "$$REF" --format='get(image_summary.digest)')
       echo "DIGEST=$$DIGEST" > /workspace/digest
         
  # 2.6) PUBLISH (PubSub) a build-complete event with image + digest
  - id: "PUBLISH images.built"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -ceu
      - |
        source /workspace/digest
        IMAGE="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}@${DIGEST}"
        gcloud pubsub topics publish images.built \
          --message="{\"image\":\"${IMAGE}\",\"service\":\"${_SERVICE}\",\"region\":\"${_REGION}\",\"commit\":\"${COMMIT_SHA}\"}"


images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA"
