# cloudbuild.yaml
substitutions:
  _REGION: "us-east1"                         # set to your Artifact Registry + Cloud Run region
  _REPO: "cicd-artifact-repo"
  _SERVICE: "bishopllc-storefront-app"

options:
  logging: CLOUD_LOGGING_ONLY                 # or GCS_ONLY with logsBucket if preferred

steps:
  # 1) BUILD container
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA"
      - "."

  # 2) PUSH to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA"

  # 3) DEPLOY
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA"
      - "--region"
      - "${_REGION}"
      - "--service-account"
      - cicd-runtime@warm-capsule-470118-i5.iam.gserviceaccount.com
      - "--allow-unauthenticated"

      # add one of:
      # - "--allow-unauthenticated"   # if public
      # or use IAM/ingress controls as required
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA"
