# clouddeploy.yaml (deploy-by-digest from images.approved)

substitutions:
  _SERVICE: "bishopllc-storefront-app"
  _REGION: "us-east1"
  _ATTESTOR: "itsec-approver"                 # use the exact attestor name that policy requires
  _ATTESTOR_PROJECT: "warm-capsule-470118-i5"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: "extract approved image"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -ceu
      - |
        echo "$BUILD_TRIGGER_MESSAGE" | tee /workspace/approved.json
        IMAGE=$(jq -r '.image // empty' /workspace/approved.json)
        [[ -n "$IMAGE" ]] || { echo "images.approved message missing .image"; exit 2; }
        echo "IMAGE=$IMAGE" | tee /workspace/image.txt

  - id: "verify attestation exists"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -ceu
      - |
        source /workspace/image.txt
        gcloud container binauthz attestations list \
          --artifact-url="$IMAGE" \
          --attestor="$_ATTESTOR" \
          --attestor-project="$_ATTESTOR_PROJECT" \
          --format="value(name)" | grep -q . || {
          echo "No attestation found for $IMAGE and $_ATTESTOR"; exit 1; }

  - id: "deploy by digest"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -ceu
      - |
        source /workspace/image.txt
        gcloud run deploy "$_SERVICE" --image "$IMAGE" --region "$_REGION"
