# cloudbuild.yaml
substitutions:
  _REGION: "us-east1"                         # set to your Artifact Registry + Cloud Run region
  _REPO: "cicd-artifact-repo"
  _SERVICE: "bishopllc-storefront-app"

options:
  logging: CLOUD_LOGGING_ONLY                 # or GCS_ONLY with logsBucket if preferred

steps:
  # 1) BUILD container
  - id: "BUILD docker container"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA"
      - "."

  # 2) PUSH to Artifact Registry
  - id: "PUSH to Artifact Registry"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA"

  # 2.5) LOOK UP DIGEST for the just-pushed tag
  - id: "RESOLVE digest"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -ceu
      - |
       REF="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA"
       DIGEST=$(gcloud artifacts docker images describe "$$REF" --format='get(image_summary.digest)')
       echo "DIGEST=$$DIGEST" > /workspace/digest
      

  # 3) DEPLOY
  - id: "DEPLOY to Cloud Run Environment"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -ceu
      - |
        source /workspace/digest
        gcloud run deploy "${_SERVICE}" \
          --image "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}@$$DIGEST" \
          --region "${_REGION}" \
          --service-account cicd-runtime@warm-capsule-470118-i5.iam.gserviceaccount.com      


images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA"
